
import bag from "/assets/images/bag.svg";
import milktea from "/assets/images/milktea-logo.svg";
import bubbletea from "/assets/images/milktea.png";
import quality from "/assets/images/quality.svg";
import flavor from "/assets/images/flavors.svg";
import sugar from "/assets/images/sugar.svg";
import sustain from "/assets/images/sustain.svg";
import strawberry from "/assets/images/strawberry.png";
import choco from "/assets/images/chocooverload.jpg";
import avocado from "/assets/images/avocado.jpg";
import mango from "/assets/images/mango.png";
import bubble from "/assets/images/bubbletea.jpg";
import allseason from "/assets/images/allseason.jpg";
import kiwi from "/assets/images/kiwi.jpg";
import apple from "/assets/images/apple.jpg";
import facebook from "/assets/images/facebook.svg";
import instagram from "/assets/images/instagram.svg";
import tiktok from "/assets/images/tiktok.svg";
import twitter from "/assets/images/twitter.svg";

export const bagImg = bag;
export const milkteaLogo = milktea;
export const bubblemilktea = bubbletea;
export const qualityImg = quality;
export const flavorImg = flavor;
export const sugarImg = sugar;
export const sustainImg = sustain;
export const strawberryImg = strawberry;
export const chocoImg = choco;
export const avocadoImg = avocado;
export const mangoImg = mango;
export const bubbleImg = bubble;
export const allseasonImg = allseason;
export const kiwiImg = kiwi;
export const appleImg = apple;
export const facebookIcon = facebook;
export const instagramIcon = instagram;
export const tiktokIcon = tiktok;
export const twitterIcon = twitter;
