
import bag from "/assets/svg/bag.svg";
import milktea from "/assets/images/dleecioustea-logo.png";
import bubbletea from "/assets/images/milktea.png";
import quality from "/assets/svg/quality.svg";
import flavor from "/assets/svg/flavors.svg";
import sugar from "/assets/svg/sugar.svg";
import sustain from "/assets/svg/sustain.svg";
import strawberry from "/assets/images/Strawberry-Milktea.png";
import matcha from "/assets/images/Matcha-Milktea.png";
import okinawa from "/assets/images/Okinawa-Milktea.png";
import thai from "/assets/images/Thai-Milktea.png";
import caramel from "/assets/images/Caramel-Milktea.png";
import choco from "/assets/images/chocooverload.jpg";
import avocado from "/assets/images/avocado.jpg";
import mango from "/assets/images/mango.png";
import bubble from "/assets/images/bubbletea.jpg";
import allseason from "/assets/images/allseason.jpg";
import kiwi from "/assets/images/kiwi.jpg";
import apple from "/assets/images/apple.jpg";

export const bagImg = bag;
export const milkteaLogo = milktea;
export const bubblemilktea = bubbletea;
export const qualityImg = quality;
export const flavorImg = flavor;
export const sugarImg = sugar;
export const sustainImg = sustain;
export const strawberryImg = strawberry;
export const matchaImg = matcha;
export const okinawaImg = okinawa;
export const thaiImg = thai;
export const caramelImg = caramel;
export const chocoImg = choco;
export const avocadoImg = avocado;
export const mangoImg = mango;
export const bubbleImg = bubble;
export const allseasonImg = allseason;
export const kiwiImg = kiwi;
export const appleImg = apple;
